---
- hosts: all

  vars_files:
    - default.config.yml

  tasks:
    - include: tasks/dnf.yml
    - include: tasks/dotfiles.yml
    - include: tasks/docker.yml
    - include: tasks/golang.yml
    - include: tasks/fzf.yml
